platform :ios, '8.0'
#use_frameworks!

target 'TCMLocationKit_Example' do
  pod 'TCMLocationKit', :path => '../'

  target 'TCMLocationKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'MJExtension'
  end
end
